[build]
builder = "dockerfile"
dockerfilePath = "NoteIt/Dockerfile"
dockerContext = "NoteIt"

[deploy]
healthcheckPath = "/api/auth/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10